version: "3"
services:
    # https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
    db:
        container_name: gamedb
        platform: linux/amd64
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: pongdog_app
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"